export const ABYSS_TEMPLATE_SIDEBAR_MOBILE_MAX_WIDTH = 520;

/** @deprecated Use ABYSS_TEMPLATE_SIDEBAR_MOBILE_MAX_WIDTH */
export const ABYSS_SIDEBAR_NAV_MOBILE_MAX_WIDTH = ABYSS_TEMPLATE_SIDEBAR_MOBILE_MAX_WIDTH;

/** @deprecated Use ABYSS_TEMPLATE_SIDEBAR_MOBILE_MAX_WIDTH */
export const ABYSS_SETTINGS_MOBILE_MAX_WIDTH = ABYSS_TEMPLATE_SIDEBAR_MOBILE_MAX_WIDTH;
